CREATE TABLE merchants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(255) DEFAULT NULL,
    webhook varchar(255) NOT NULL,
    tax_number varchar(9) NOT NULL,
    login varchar(255) NOT NULL,
    password varchar(80) NOT NULL,
    --
    -- timestamps
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    --
    -- constraints
    CONSTRAINT uk_merchants_tax_number UNIQUE (tax_number),
    CONSTRAINT uk_merchants_login UNIQUE (login)
);

CREATE TYPE notification_status AS ENUM (
    'CREATED',
    'SENT',
    'FAILED'
);

CREATE TYPE notification_type AS ENUM (
    'SMS',
    'EMAIL',
    'PUSH'
);

CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status notification_status NOT NULL DEFAULT 'CREATED',
    text text NOT NULL,
    merchant_id bigint NOT NULL,
    type notification_type NOT NULL,
    receiver_info varchar(255) NOT NULL,
    --
    -- timestamps
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    --
    -- relations
    CONSTRAINT fk_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE RESTRICT
);

CREATE TABLE price (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_active boolean DEFAULT TRUE,
    price bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);