CREATE TABLE invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id bigint NOT NULL,
    invoice_month INTEGER NOT NULL,
    invoice_year INTEGER NOT NULL,
    notification_count INTEGER NOT NULL,
    --
    -- timestamps
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    --
    -- relations
    CONSTRAINT fk_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE RESTRICT,
     --
     -- constraints
     CONSTRAINT uk_invoice_merchant_id_month_year UNIQUE (merchant_id, invoice_month, invoice_year)
)